In [1]:
import numpy as np
arr = [6,7,8,9]
print(type(arr))

<class 'list'>


In [2]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.dtype)
print(a.shape)
print(a.ndim)

int32
(4,)
1


In [10]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)
b.shape

[[1 2 3]
 [4 5 6]]
2


(2, 3)

In [16]:
np.random.random((2,3))
np.zeros((2,3))
np.ones((2,3))
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
import pandas as pd
days = pd.Series(['Monday', 'Tuesday', 'Wednesday'])
print(days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [22]:
dayl = np.array(['Monday', 'Tuesday', 'Wednesday'])
nd = pd.Series(dayl)
print(nd)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [23]:
import pandas as pd
days = pd.Series(['Monday', 'Tuesday', 'Wednesday'], index=['a','b','c'])
print(days)

a       Monday
b      Tuesday
c    Wednesday
dtype: object


In [32]:
print(pd.DataFrame())
df_dict = {'Country': ['Ghana', 'Kenya', 'Nigeria', 'Togo'],
'Capital': ['Accra', 'Nairobi', 'Abuja', 'Lome'], 'Population': [10000, 8500, 35000, 12000 ], 'Age': [60, 70, 80, 75]
}
df = pd.DataFrame (df_dict, index= [2, 4, 6, 8]) 
df_list = [
['Ghana', 'Accra', 10000, 60], ['Kenya', 'Nairobi', 8500, 70], ['Nigeria', 'Abuja', 35000, 80], ['Togo', 'Lome', 12000, 75]
]
df1 = pd.DataFrame(df_list, columns = ['Country', 'Capital', 'Population', 'Age'], index = [2,4,6,8])
print(df)
print(df1)
df.iloc[3]
df.loc[6]
df['Population'].sum()
df.sum()
df.mean()
df.describe()
df.dropna()

Empty DataFrame
Columns: []
Index: []
   Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75
   Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75


C:\Users\dgp\AppData\Local\Temp\ipykernel_13652\4170638714.py:16: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()


Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75

In [46]:
url = 'https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv'
fd = pd.read_csv(url, error_bad_lines = False)
fd.describe(include = 'all')
fd.isnull().sum()
fd.groupby('fuel_unit')['fuel_unit'].count()
fd.duplicated().any()

C:\Users\dgp\AppData\Local\Temp\ipykernel_13652\1279997191.py:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  fd = pd.read_csv(url, error_bad_lines = False)


False